const characters = [
  {
    id: 1,
    name: "Jay",
    emoji: "👨‍💼",
    avatarURL: "images/dimitris.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 2,
    name: "Olivia",
    emoji: "👩‍🦰",
    avatarURL: "images/maria.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: true,
    },
  },
  {
    id: 3,
    name: "Jack",
    emoji: "👨‍🎨",
    avatarURL: "images/nikos.jpeg",
    traits: {
      glasses: true,
      hat: true,
      beard: false,
      smile: false,
    },
  },
  {
    id: 4,
    name: "Sarah",
    emoji: "👩‍🔬",
    avatarURL: "images/sofia.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 5,
    name: "Logan",
    emoji: "👨‍🍳",
    avatarURL: "images/giorgos.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: true,
      smile: false,
    },
  },
  {
    id: 6,
    name: "Fatima",
    emoji: "👩‍💻",
    avatarURL: "images/eleni.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: false,
      smile: false,
    },
  },
  {
    id: 7,
    name: "Kostas",
    emoji: "👨‍⚕️",
    avatarURL: "images/kostas.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: true,
      smile: true,
    },
  },
  {
    id: 8,
    name: "Anna",
    emoji: "👩‍🏫",
    avatarURL: "images/anna.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: false,
    },
  },
  {
    id: 9,
    name: "Abdullah",
    emoji: "👨‍🔧",
    avatarURL: "images/panagiotis.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: true,
      smile: true,
    },
  },
  {
    id: 10,
    name: "Nora",
    emoji: "👩‍🎤",
    avatarURL: "images/katerina.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 11,
    name: "Henry",
    emoji: "👨‍🚀",
    avatarURL: "images/yannis.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: true,
    },
  },
  {
    id: 12,
    name: "Layla",
    emoji: "👩‍⚖️",
    avatarURL: "images/vasiliki.jpeg",
    traits: {
      glasses: true,
      hat: true,
      beard: false,
      smile: false,
    },
  },
  {
    id: 13,
    name: "Steven",
    emoji: "👨‍🌾",
    avatarURL: "images/michalis.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: true,
      smile: true,
    },
  },
  {
    id: 14,
    name: "Chiamaka",
    emoji: "👩‍🎨",
    avatarURL: "images/despina.jpeg",
    traits: {
      glasses: true,
      hat: true,
      beard: false,
      smile: true,
    },
  },
  {
    id: 15,
    name: "Gui",
    emoji: "👨‍🎓",
    avatarURL: "images/alexandros.jpeg",
    traits: {
      glasses: true,
      hat: true,
      beard: false,
      smile: true,
    },
  },
  {
    id: 16,
    name: "Melati",
    emoji: "👩‍🔬",
    avatarURL: "images/ioanna.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: false,
    },
  },
  {
    id: 17,
    name: "Cameron",
    emoji: "👨‍💻",
    avatarURL: "images/christos.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 18,
    name: "Maria",
    emoji: "👩‍🌾",
    avatarURL: "images/fotini.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: false,
      smile: false,
    },
  },
  {
    id: 19,
    name: "Zahid",
    emoji: "👨‍🏫",
    avatarURL: "images/stavros.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: true,
      smile: false,
    },
  },
  {
    id: 20,
    name: "Asha",
    emoji: "👩‍✈️",
    avatarURL: "images/antonia.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 21,
    name: "Gabriel",
    emoji: "👨‍🚒",
    avatarURL: "images/petros.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: true,
      smile: true,
    },
  },
  {
    id: 22,
    name: "Zoe",
    emoji: "👩‍🍳",
    avatarURL: "images/zoe.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: true,
    },
  },
  {
    id: 23,
    name: "Vladimir",
    emoji: "👨‍🎤",
    avatarURL: "images/andreas.jpeg",
    traits: {
      glasses: true,
      hat: true,
      beard: false,
      smile: false,
    },
  },
  {
    id: 24,
    name: "Hoa",
    emoji: "👩‍🚒",
    avatarURL: "images/chrysa.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: false,
      smile: true,
    },
  },
];
