const characters = [
  {
    id: 1,
    name: "Dimitris",
    emoji: "👨‍💼",
    avatarURL: "images/dimitris.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 2,
    name: "Maria",
    emoji: "👩‍🦰",
    avatarURL: "images/maria.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: true,
    },
  },
  {
    id: 3,
    name: "Nikos",
    emoji: "👨‍🎨",
    avatarURL: "images/nikos.jpeg",
    traits: {
      glasses: true,
      hat: true,
      beard: false,
      smile: false,
    },
  },
  {
    id: 4,
    name: "Sofia",
    emoji: "👩‍🔬",
    avatarURL: "images/sofia.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 5,
    name: "Giorgos",
    emoji: "👨‍🍳",
    avatarURL: "images/giorgos.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: true,
      smile: false,
    },
  },
  {
    id: 6,
    name: "Eleni",
    emoji: "👩‍💻",
    avatarURL: "images/eleni.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: false,
      smile: false,
    },
  },
  {
    id: 7,
    name: "Kostas",
    emoji: "👨‍⚕️",
    avatarURL: "images/kostas.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: true,
      smile: true,
    },
  },
  {
    id: 8,
    name: "Anna",
    emoji: "👩‍🏫",
    avatarURL: "images/anna.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: false,
    },
  },
  {
    id: 9,
    name: "Panagiotis",
    emoji: "👨‍🔧",
    avatarURL: "images/panagiotis.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: true,
      smile: false,
    },
  },
  {
    id: 10,
    name: "Katerina",
    emoji: "👩‍🎤",
    avatarURL: "images/katerina.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 11,
    name: "Yannis",
    emoji: "👨‍🚀",
    avatarURL: "images/yannis.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: true,
    },
  },
  {
    id: 12,
    name: "Vasiliki",
    emoji: "👩‍⚖️",
    avatarURL: "images/vasiliki.jpeg",
    traits: {
      glasses: true,
      hat: true,
      beard: false,
      smile: false,
    },
  },
  {
    id: 13,
    name: "Michalis",
    emoji: "👨‍🌾",
    avatarURL: "images/michalis.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: true,
      smile: true,
    },
  },
  {
    id: 14,
    name: "Despina",
    emoji: "👩‍🎨",
    avatarURL: "images/despina.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 15,
    name: "Alexandros",
    emoji: "👨‍🎓",
    avatarURL: "images/alexandros.jpeg",
    traits: {
      glasses: true,
      hat: true,
      beard: false,
      smile: true,
    },
  },
  {
    id: 16,
    name: "Ioanna",
    emoji: "👩‍🔬",
    avatarURL: "images/ioanna.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: false,
    },
  },
  {
    id: 17,
    name: "Christos",
    emoji: "👨‍💻",
    avatarURL: "images/christos.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 18,
    name: "Fotini",
    emoji: "👩‍🌾",
    avatarURL: "images/fotini.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: false,
      smile: false,
    },
  },
  {
    id: 19,
    name: "Stavros",
    emoji: "👨‍🏫",
    avatarURL: "images/stavros.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: true,
      smile: false,
    },
  },
  {
    id: 20,
    name: "Antonia",
    emoji: "👩‍✈️",
    avatarURL: "images/antonia.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: false,
      smile: true,
    },
  },
  {
    id: 21,
    name: "Petros",
    emoji: "👨‍🚒",
    avatarURL: "images/petros.jpeg",
    traits: {
      glasses: true,
      hat: false,
      beard: true,
      smile: true,
    },
  },
  {
    id: 22,
    name: "Zoe",
    emoji: "👩‍🍳",
    avatarURL: "images/zoe.jpeg",
    traits: {
      glasses: false,
      hat: true,
      beard: false,
      smile: true,
    },
  },
  {
    id: 23,
    name: "Andreas",
    emoji: "👨‍🎤",
    avatarURL: "images/andreas.jpeg",
    traits: {
      glasses: true,
      hat: true,
      beard: true,
      smile: false,
    },
  },
  {
    id: 24,
    name: "Chrysa",
    emoji: "👩‍🚒",
    avatarURL: "images/chrysa.jpeg",
    traits: {
      glasses: false,
      hat: false,
      beard: false,
      smile: false,
    },
  },
];
